# Generated by Django 6.0.5 on 2026-08-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='contact_no',
        ),
        migrations.AddField(
            model_name='user',
            name='date_format',
            field=models.CharField(choices=[('F j, Y', 'Month DD, YYYY (June 1, 2026)'), ('m/d/Y', 'MM/DD/YYYY'), ('Y-m-d', 'YYYY-MM-DD')], default='F j, Y', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='time_format',
            field=models.CharField(choices=[('12', '12-hour (AM/PM)'), ('24', '24-hour')], default='12', max_length=2),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Manila', max_length=50),
        ),
    ]
