# Generated by Django 6.0.5 on 2026-09-14 09:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('DOCUMENT_UPDATES', 'Document Updates'), ('SUBMISSION_UPDATES', 'Submission Updates'), ('SUBMISSION_REMINDERS', 'Submission Reminders'), ('APPROVAL_REJECTIONS', 'Approval and Rejections'), ('SECURITY_ALERTS', 'Security Alerts')], max_length=30)),
                ('enabled', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('system_enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'notification_type'), name='unique_user_notification_type')],
            },
        ),
    ]
