# Generated by Django 6.0.5 on 2026-09-17 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_faculty_submissions', models.BooleanField(default=True)),
                ('return_for_revisions', models.BooleanField(default=True)),
                ('create_submission_bins', models.BooleanField(default=True)),
                ('edit_submission_bin', models.BooleanField(default=True)),
                ('view_approved_documents', models.BooleanField(default=True)),
                ('add_faculty_users', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Staff Permission',
                'verbose_name_plural': 'Staff Permissions',
            },
        ),
    ]
