# Generated by Django 6.0.5 on 2026-09-18 03:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_staffpermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.profile_photo_path),
        ),
    ]
