# Generated by Django 6.0.5 on 2026-09-01 02:35

import django.db.models.deletion
import submissions.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=submissions.models.revision_upload_path)),
                ('version_number', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='DocumentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_remarks', to=settings.AUTH_USER_MODEL)),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='submissions.documentrevision')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('PENDING_APPROVAL', 'Reviewed - Pending Approval'), ('NEEDS_REVISION', 'Needs Revision'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved')], default='SUBMITTED', max_length=30)),
                ('document_file', models.FileField(upload_to=submissions.models.submission_upload_path)),
                ('is_pinned', models.BooleanField(default=False)),
                ('initially_submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('revisioned_at', models.DateTimeField(blank=True, null=True)),
                ('resubmitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_submissions', to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='documentrevision',
            name='submission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='submissions.documentsubmission'),
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement_title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('academic_term', models.CharField(max_length=255)),
                ('semester', models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('SUMMER', 'Summer')], default='FIRST', max_length=10)),
                ('deadline', models.DateTimeField()),
                ('assigned_to', models.CharField(choices=[('ALL', 'All Faculty'), ('FULL_TIME', 'Full-Time Faculty'), ('PART_TIME', 'Part-Time Faculty')], default='ALL', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('requirement_title', 'academic_term', 'semester'), name='unique_requirement_per_term_semester')],
            },
        ),
        migrations.CreateModel(
            name='DraftUpload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('draft_file', models.FileField(blank=True, upload_to=submissions.models.draft_upload_path)),
                ('draft_created_at', models.DateTimeField(auto_now_add=True)),
                ('draft_updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_uploads', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draft_uploads', to='submissions.requirement')),
            ],
        ),
        migrations.AddField(
            model_name='documentsubmission',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='submissions.requirement'),
        ),
        migrations.AddConstraint(
            model_name='documentrevision',
            constraint=models.UniqueConstraint(fields=('submission', 'version_number'), name='unique_submission_version'),
        ),
        migrations.AddConstraint(
            model_name='draftupload',
            constraint=models.UniqueConstraint(fields=('faculty', 'requirement'), name='unique_faculty_requirement_draft'),
        ),
    ]
