# Generated by Django 6.0.5 on 2026-08-27 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentsubmission',
            old_name='is_favorite',
            new_name='is_pinned',
        ),
        migrations.AddField(
            model_name='requirement',
            name='semester',
            field=models.CharField(choices=[('FIRST', 'First Semester'), ('SECOND', 'Second Semester'), ('SUMMER', 'Summer')], default='FIRST', max_length=10),
        ),
    ]
