# Generated by Django 6.0.5 on 2026-08-27 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_rename_is_favorite_documentsubmission_is_pinned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='requirement_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='requirement',
            constraint=models.UniqueConstraint(fields=('requirement_title', 'academic_term', 'semester'), name='unique_requirement_per_term_semester'),
        ),
    ]
